tmux/bash: New SP1/status conf

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -46,9 +46,24 @@ pchar_error=$(echo -e "\001\033[0;31m\002")
 neutral_char=$(echo -e "\u2237")
 no_error_char=$(echo -e "\u2591")
 unix_tools_os=$(uname -a)
+is_remote=1
+
+prinrc_prompt() {
+  if [[ 0 != "$1" ]]; then
+    echo -n "${pchar_error}E${pchar_blank}"
+  else
+    echo -n "["
+  fi
+}
 
 
-PS1='`${TOOLS_BIN_PATH}/cppprompt $? "$(pwd)" 38 --color "${pchar_blank}:${pchar_blank}:${pchar_blank}:${pchar_folder_sep}:${pchar_error}" --truncate 6 --chars "${no_error_char}${neutral_char}"`\[\033[01;31m\]\$\[\033[00m\] '
+if [[ -n "${TMUX:-}" ]]; then
+  PS1='$(prinrc_prompt $?)${pchar_error}@:${pchar_blank}$(printf "%s" ${PWD##*/})/]\[\033[01;31m\]$\[\033[00m\] '
+else
+  PS1='$(prinrc_prompt $?)\u${pchar_error}@${pchar_blank}\h${pchar_error}:${pchar_blank}$(printf "%s" ${PWD##*/})/]\[\033[01;31m\]$\[\033[00m\] '
+fi
+
+
 
 # Completion
 if [ -f /etc/bash_completion ]; then
